const REQUESTING_API = 'REQUESTING_API';
const RECEIVED_API_RESPONSE = 'RECEIVED_API_RESPONSE';
const CALL_API = 'CALL_API';
const RECEIVED_APT_EXCEPTION = 'RECEIVED_APT_EXCEPTION';

export default {

	REQUESTING_API,
	RECEIVED_API_RESPONSE,
	CALL_API,
	RECEIVED_APT_EXCEPTION
}